### PR TITLE
#20 - Implemented <<Go to item>> functionality in Bookmarks Overview.

### PR DESCRIPTION
**Pull request by adelinsofrag**

### CODE REVIEW

**Comment by f-ricci** [comment]
Fixed conflicts in order to merge

**Comment by adelinsofrag** [comment]
Should be ok.

**Comment by f-ricci** [comment]
@adelinsofrag resolve conflict in order to merge the code

**Comment by adelinsofrag** [comment]
Fixed conflicts.

**Comment by adelinsofrag** [comment]
@f-ricci this should be ok now

**Pull request merged**
